 const niyetler = [
      "Bugün kendime şefkatle yaklaşmayı seçiyorum.",
      "Her adımım beni hedefime bir adım daha yaklaştırıyor.",
      "Başarılar beni bekliyor, sabırlı olacağım.",
      "İlham veren insanlarla çevriliyim.",
      "Zorluklar beni daha güçlü kılıyor.",
      "Günüm neşeyle dolsun.",
      "Kendi değerimin farkındayım.",
      "Yeni fırsatlara açığım.",
      "Dengeyi buluyorum.",
      "Kariyerimde yeni bir sayfa açılıyor.",
      "Huzurla dolu bir gün diliyorum.",
      "Yaratıcılığım bugün sınır tanımayacak.",
      "Olumlu enerjiyi çevreme yayıyorum.",
      "Sevgi dolu ilişkiler kuruyorum.",
      "Kendime ve vizyonuma inanıyorum.",
      "Hayat bana mucizeler sunuyor.",
      "Her şey olması gerektiği gibi oluyor.",
      "Bugün fark yaratacağım.",
      "Cesur ve kararlıyım.",
      "İçsel rehberimi dinliyorum.",
      "Düşüncelerim gerçeğimi şekillendiriyor.",
      "Yeni bilgiler öğrenmeye hazırım.",
      "Yaratıcı çözümler buluyorum.",
      "Hayatı sevgiyle kucaklıyorum.",
      "Kendimi sürekli geliştiriyorum.",
      "Hayatımı tutkuyla yaşıyorum.",
      "Zihnim berrak, kalbim açık.",
      "Güzel sürprizlerle dolu bir gün bekliyor.",
      "Bugün geçmişi bırakıp ileriye bakıyorum.",
      "Yeni başlangıçlara hazırım.",
      "İçimdeki ışık yolumu aydınlatıyor.",
      "Etrafıma ilham veriyorum.",
      "Başarının bana geldiğini hissediyorum.",
      "Her şey zamanında olur.",
      "Şükretmeyi hatırlıyorum.",
      "Bugün her şey benim için kolaylıkla akacak.",
      "İletişimim net ve etkili.",
      "Güçlü bir vizyona sahibim.",
      "Küçük adımlar büyük değişimleri başlatır.",
      "Kendime değer veriyorum.",
      "Bugün enerjim yüksek.",
      "Hayatın sunduğu güzellikleri fark ediyorum.",
      "Her zorluk bir öğretmendir.",
      "Yeni fırsatlara yüreğim açık.",
      "Gelişmeye ve dönüşmeye hazırım.",
      "Geçmişimi sevgiyle uğurluyorum.",
      "Kendimi olduğum gibi kabul ediyorum.",
      "İç huzurumu koruyorum.",
      "Hayatıma bolluk ve bereket çekiyorum.",
      "Bugün harika bir başlangıç yapıyorum.",
      "Kendi potansiyelimin farkındayım.",
      "Her nefesimde güç hissediyorum.",
      "Kelimelerim şifa veriyor.",
      "Yönümü buluyorum.",
      "Akışa güveniyorum.",
      "Bugün hayallerime bir adım daha yaklaşıyorum.",
      "Kalbim açık, zihnim berrak.",
      "İşlerim kolaylıkla ilerliyor.",
      "Her gün öğreniyor ve büyüyorum.",
      "Başarı benimle.",
      "Zamanı etkili kullanıyorum.",
      "Her anda güzellikleri fark ediyorum.",
      "Kendimle gurur duyuyorum.",
      "Bugün beni destekleyen fırsatlar doğuyor.",
      "İçsel sezgilerim yol gösterici.",
      "Düşüncelerim güçlü ve yaratıcı.",
      "Hayat bana destek oluyor.",
      "Doğru zamanda, doğru yerdeyim.",
      "Yaratıcılığım akıyor.",
      "Bugün her şey uyum içinde.",
      "Ruhsal olarak dengedeyim.",
      "Kararlarımı güvenle alıyorum.",
      "Geleceğe umutla bakıyorum.",
      "Duygularımı sağlıklı şekilde ifade ediyorum.",
      "Daha iyi bir versiyonuma evriliyorum.",
      "Bugün cesur adımlar atıyorum.",
      "Hayatın ritmine uyum sağlıyorum.",
      "Yolum açık, niyetim net.",
      "Her şey sevgiyle ilerliyor.",
      "Doğa bana ilham veriyor.",
      "Hayatımda denge ve uyum var.",
      "Yeni deneyimlere hazırım.",
      "Kalbimde sevgi taşıyorum.",
      "Bugün farkındalıkla yaşıyorum.",
      "Günüm sakin ve verimli geçiyor.",
      "Hayallerim gerçek oluyor.",
      "Kendimi geliştirmek için harika bir fırsat.",
      "Her an yeni bir başlangıç.",
      "Hedeflerim net ve ulaşılabilir.",
      "İçimdeki cesaret beni yönlendiriyor.",
      "Bugün bana mutluluk getiriyor.",
      "Hayatımda her şey yolunda.",
      "Kendime sadık kalıyorum.",
      "Fırsatları fark edip değerlendiriyorum.",
      "Bugün bana ilham veriyor.",
      "Kendimi özgür hissediyorum.",
      "Yeni bir enerjiyle doluyum.",
      "Bugün geçmişten özgürleşiyorum.",
      "Ruhum hafifliyor.",
      "Her şey bir düzen içinde.",
      "Hayat bana yeni yollar gösteriyor.",
      "Bugün verimli bir gün olacak."
    ];

    window.onload = () => {
  const rastgeleNiyet = niyetler[Math.floor(Math.random() * niyetler.length)];
  document.querySelector(".message").innerText = rastgeleNiyet;

  const accessKey = "Ep6jy0GfSXBhRqWuV3h2STQSnzjIQHRxnRf42ostnnM";
  const query = "nature landscape";

  fetch(`https://api.unsplash.com/photos/random?query=${query}&client_id=${accessKey}`)
    .then(response => response.json())
    .then(data => {
      const bgImage = document.getElementById("bg-image");
      bgImage.src = data.urls.full;
      bgImage.alt = data.alt_description || "Doğa manzarası";
    })
    .catch(error => console.error("Arka plan alınamadı:", error));
    };
 
